Add a cluster role for submariner-engine serivce-account
submariner-io/submariner-charts pull request #106
Opened 2021-01-13 17:09 UTC by aswinsuryan

The submainer-engine now access the node object as part
of golbalnet-healthcheck support and the required roles are
added

Signed-off-by: Aswin Surayanarayanan <asuryana@redhat.com>

2021-01-13 17:38 UTC, tpantelis approved these changes

2021-01-13 19:25 UTC, sridhargaddam requested changes

2021-01-13 19:25 UTC, sridhargaddam commented on submariner/templates/rbac.yaml
> +  verbs: ["get", "list", "watch", "update"]
I dont think we require "update"

2021-01-14 06:24 UTC, aswinsuryan commented on submariner/templates/rbac.yaml
> +  verbs: ["get", "list", "watch", "update"]
removed.

2021-01-14 08:30 UTC, skitt approved these changes

2021-01-14 09:18 UTC, sridhargaddam approved these changes
Thanks for addressing the comments @aswinsuryan

2021-01-14 09:33 UTC, merged