Add support for the IPAM
submariner-io/submariner-charts pull request #12
Opened 2020-01-08 09:55 UTC by mkolesnik

Added a chart for the ipam controller which uses the global CIDR.
Also added the global CIDR to the submariner engine pod env so it can
utilize it.
The IPAM controller will only be deployed if the CIDR is specified.

2020-01-08 13:08 UTC, sridhargaddam requested changes

2020-01-08 13:08 UTC, sridhargaddam commented on submariner/templates/globalnet-ipam.yaml
> +kind: Deployment
As discussed, please change this to DaemonSet

2020-01-08 13:08 UTC, sridhargaddam commented on submariner/values.yaml
> +  globalCidr: ""
AFAIU, this is optional, but there is no harm in having it. So, let's keep it.

2020-01-08 13:08 UTC, sridhargaddam commented on submariner/templates/globalnet-ipam.yaml
> +    app: {{ template "submariner.fullname" . }}-ipam
Things have changed a bit since the original implementation. Please take a look at the file deploy-globalnet-2.yaml in the following PR - https://github.com/submariner-io/submariner/pull/265/files

2020-01-08 13:08 UTC, sridhargaddam commented on submariner/templates/globalnet-ipam.yaml
> +  name: {{ template "submariner.fullname" . }}-ipam
Originally we used to call it ipam controller but we changed it to globalnet controller. In the commit message for this PR, please use globalnet controller. Thanks for working on this patch.

2020-01-13 08:25 UTC, mkolesnik commented on submariner/templates/globalnet-ipam.yaml
> +kind: Deployment
Done

2020-01-13 08:26 UTC, mkolesnik commented on submariner/templates/globalnet-ipam.yaml
> +    app: {{ template "submariner.fullname" . }}-ipam
I've updated the PR

2020-01-13 08:26 UTC, mkolesnik commented on submariner/templates/globalnet-ipam.yaml
> +  name: {{ template "submariner.fullname" . }}-ipam
Updated the PR

2020-01-13 08:27 UTC, mkolesnik commented on submariner/values.yaml
> +  globalCidr: ""
Sure, I put it since deploying without globalnet sounds like a sane default to me

2020-01-14 08:19 UTC, sridhargaddam approved these changes
One observation regarding Serviceaccount and rolebinding. Other than this, it LGTM. Thanks for working on it Mike.

2020-01-14 08:19 UTC, sridhargaddam commented on submariner/templates/globalnet.yaml
> +kind: DaemonSet
For the successful deployment of this DaemonSet, we also require the corresponding ServiceAccount and Rolebinding.

Currently, its done as part of e2e.sh file in overlapping-cidrs branch [1]. I tried this patch locally and could see that eventhough globalnet DaemonSet was deployed, due to the missing serviceaccount (/rolebindings), its not running. Can you please take a look at it. I'm fine if you want to address it in a seperate patch.

[1] https://github.com/submariner-io/submariner/blob/db8ecc23706a644d8d46688e2ac390f77b6ef8f4/scripts/kind-e2e/e2e.sh#L336
[role-binding-file] take a look at role-globalnet.yaml in https://github.com/submariner-io/submariner/pull/265/files

2020-01-16 06:59 UTC, vthapar commented on submariner/templates/globalnet.yaml
> +kind: DaemonSet
I'd prefer ServiceAccount and RoleBinding to come in this patch itself. That way we won't have some work done through charts and some through e2e.sh

2020-01-16 07:01 UTC, vthapar approved these changes
Looks good. Except for ServiceAccount and Rolebinding changes. Okay with them coming in subsequent patch, will let you make a call on it.

2020-01-16 07:06 UTC, sridhargaddam commented on submariner/templates/globalnet.yaml
> +kind: DaemonSet
@mkolesnik let us know how you would like to take it forward. Do you want to update the same patch or prefer to push a new PR, based on that we can decide whether to merge this PR or wait.

2020-01-16 14:35 UTC, mkolesnik commented on submariner/templates/globalnet.yaml
> +kind: DaemonSet
I can do it in the same or a new patch, whatever you guys prefer let me know

2020-01-16 14:43 UTC, sridhargaddam commented on submariner/templates/globalnet.yaml
> +kind: DaemonSet
Cool, So, let's do it in the same PR.

2020-01-19 10:28 UTC, sridhargaddam requested changes

2020-01-19 10:28 UTC, sridhargaddam commented on submariner/templates/globalnet.yaml
> +              value: '{{ .Values.submariner.globalCidr }}'
@mkolesnik you can remove this environment variable from the globalnet DaemonSet as we will now be reading this information from the clusterCRD. The following patch handles this change - https://github.com/submariner-io/submariner/pull/293

2020-01-20 07:03 UTC, mkolesnik commented on submariner/templates/globalnet.yaml
> +              value: '{{ .Values.submariner.globalCidr }}'
Sure, thanks

2020-01-23 14:13 UTC, mangelajo commented on submariner/templates/globalnet.yaml
> +kind: DaemonSet
this seems resolved

2020-01-23 18:09 UTC, sridhargaddam requested changes

2020-01-23 18:09 UTC, sridhargaddam commented on submariner/templates/svc-acct.yaml
> +{{- if .Values.serviceAccounts.globalnet.create }}
I'm seeing the following error as part of Submariner Globalnet DaemonSet (and because of this GN PODs are not running)

│  Warning  FailedCreate  91s (x16 over 4m15s)  daemonset-controller  Error creating: pods "submariner-globalnet-" is forbidden: error looking up service account submariner/submariner-globa│
│lnet: serviceaccount "submariner-globalnet" not found

2020-01-23 18:09 UTC, sridhargaddam commented on submariner/templates/rbac.yaml
> +  resources: ["endpoints"]
Since Globalnet Controller will now be reading the clusterCRD for globalCIDR, it needs ClusterRole for "clusters".

Please include "clusters" in the resources field.
i.e., resources: ["endpoints", "clusters"]

2020-01-23 18:34 UTC, sridhargaddam requested changes

2020-01-23 18:34 UTC, sridhargaddam commented on submariner/templates/svc-acct.yaml
> +{{- if .Values.serviceAccounts.globalnet.create }}
Looks like the error because we configured globalnet as false in submariner/values.yaml

Can we modify the "if" condition to check if globalCidr is present/not and based on that create ServiceAccount?

2020-01-27 14:40 UTC, mkolesnik commented on submariner/templates/rbac.yaml
> +  resources: ["endpoints"]
Will do

2020-01-27 14:40 UTC, mkolesnik commented on submariner/templates/svc-acct.yaml
> +{{- if .Values.serviceAccounts.globalnet.create }}
Oh, I did it like that to keep it consistent with the rest of the service accounts creation logic. Perhaps we can change it in a later patch with the rest of service account creation logic so it doesn't look weird.

2020-01-27 14:47 UTC, sridhargaddam requested changes

2020-01-27 14:47 UTC, sridhargaddam commented on submariner/templates/svc-acct.yaml
> +{{- if .Values.serviceAccounts.globalnet.create }}
Currently with this PR, even if we try to deploy clusters with globalCIDR, its not functional because serviceAccount is not created.
Personally, I feel that if the change is small, we can do it as part of this PR so that we have a full PR that adds the necessary helm support for deploying globalnetController. What do you say?

2020-01-27 15:01 UTC, mkolesnik commented on submariner/templates/svc-acct.yaml
> +{{- if .Values.serviceAccounts.globalnet.create }}
Not sure what you mean, we'd need to add this flag to the submariner helm call and it'll all work:
--set serviceAccounts.globalnet.create="true"

I don't mind to change it so much, but then it won't be consistent with how other service account creation is happening (and also not controllable by the user without altering the template itself). That's why I opted to do it the same way other service account creation is done. If we want to change this then I'd suggest we pick a uniform way which won't be different than how it's done for core submariner.

2020-01-27 15:10 UTC, sridhargaddam requested changes

2020-01-27 15:10 UTC, sridhargaddam commented on submariner/templates/svc-acct.yaml
> +{{- if .Values.serviceAccounts.globalnet.create }}
Ohk, I missed that we can specify --set serviceAccounts.globalnet.create="true" as part of helm install (along with globalCIDR) and it will create GN ServiceAccount. Okay, in that case, sure feel free to do it in a later patch.

So, please update this PR with ClusterRole including "clusters" (discussed above) and we can then merge it. Thanks.

2020-01-28 06:29 UTC, sridhargaddam approved these changes
LGTM.

2020-01-28 09:31 UTC, mangelajo approved these changes
Looks good to me.

2020-01-28 09:31 UTC, mangelajo commented on submariner/values.yaml
> +  globalCidr: ""
yes, I agree, it's nice to have, and it's good to have it empty/disabled by default :)

2020-01-28 13:06 UTC, merged