broker values
submariner-io/submariner-charts pull request #125
Opened 2021-03-04 23:44 UTC by SteveMattar

- refactor: globalnet and serviceDiscovery should be under the broker
- fix: install the broker CR

2021-03-08 18:09 UTC, dfarrell07 approved these changes
Looks great, thanks @SteveMattar!

2021-03-08 18:09 UTC, dfarrell07 commented on submariner/questions.yml
> +  description: "Enable Multi Cluster Service Discovery"
Maybe "Enable multicluster service discovery"?

2021-03-08 18:09 UTC, dfarrell07 commented on submariner-operator/questions.yml
> +  description: "Enable Multi Cluster Service Discovery"
Maybe "Enable multicluster service discovery"?

2021-03-09 19:15 UTC, dfarrell07 commented
I retriggered your CI and everything is passing now @SteveMattar. :partying_face:

2021-03-09 19:20 UTC, dfarrell07 requested changes
I think lighthouse is enabled by default and we're actually deploying with it in all cases.

2021-03-09 19:28 UTC, dfarrell07 approved these changes

2021-03-10 14:41 UTC, tpantelis approved these changes

2021-03-10 14:41 UTC, merged