Extract helm-docs generation/testing to Makefile
submariner-io/submariner-charts pull request #155
Opened 2021-07-02 12:08 UTC by dfarrell07

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

2021-07-02 12:40 UTC, tpantelis approved these changes

2021-07-05 14:35 UTC, skitt requested changes, later dismissed
The end-user instructions need to be updated ;-).

2021-07-05 14:35 UTC, skitt commented on Makefile
> +		echo "Run helm-docs, as the CI does above, and commit the updated docs."; \
```suggestion
		echo "Run make helm-docs locally (if not done already), and commit the updated docs."; \
```

2021-07-22 17:34 UTC, Jaanki approved these changes

2021-07-27 08:52 UTC, nyechiel approved these changes

2021-07-27 09:00 UTC, merged