Fix coreDNSCustomConfig values
submariner-io/submariner-charts pull request #193
Opened 2021-12-27 11:48 UTC by Negashev

What type of PR is this?

Fix coreDNSCustomConfig values

2022-01-03 09:39 UTC, skitt requested changes
Thanks for the fix! Since the template is inside a `{{- with }}` block, the references in the template should take the context into account.

2022-01-03 09:39 UTC, skitt commented on submariner-operator/templates/submariner.yaml
> +    namespace: {{ .Values.submariner.coreDNSCustomConfig.namespace }}
```suggestion
    configmapName: {{ .configmapName }}
    namespace: {{ ..namespace }}
```

2022-01-05 09:17 UTC, Negashev commented on submariner-operator/templates/submariner.yaml
> +    namespace: {{ .Values.submariner.coreDNSCustomConfig.namespace }}
Dear @skitt ,

Added changes at your suggestion

2022-01-05 09:59 UTC, skitt approved these changes

2022-01-05 12:38 UTC, tpantelis approved these changes

2022-01-05 12:47 UTC, merged