Add support for image overrides
submariner-io/submariner-charts pull request #260
Opened 2022-08-22 08:00 UTC by mkolesnik

Add support to override specific images (already supported by
submariner) to the helm chart.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-08-22 08:48 UTC, skitt requested changes

2022-08-22 08:48 UTC, skitt commented on submariner-operator/templates/submariner.yaml
> +    {{- end}}
For stylistic consistency (likewise for other `{{ end }}`s):

```suggestion
    {{- end }}
```

2022-08-22 09:10 UTC, skitt approved these changes

2022-08-22 11:54 UTC, tpantelis approved these changes

2022-08-22 12:07 UTC, merged

2022-08-30 13:18 UTC, dfarrell07 commented
@mkolesnik as discussed on PR call, this could use some docs on the website.

2022-08-31 11:53 UTC, mkolesnik commented
Thanks, added docs https://github.com/submariner-io/submariner-website/pull/820