Set chart appVersion with 'helm package' on release
submariner-io/submariner-charts pull request #294
Opened 2022-11-08 14:51 UTC by tpantelis

Use the `--app-version` parameter to `helm package` to dynamically set the chart `appVersion` field. We can then omit the hardcoded `appVersion` field in the Chart.yaml file.

The chart `version` field is also set by `helm package` but we still need to define it in the Chart.yaml file since `helm dep update` requires it. The placeholder `version` field is now set to _0.0.0_ just to give it some value.

2022-11-08 17:00 UTC, dfarrell07 approved these changes

2022-11-09 08:45 UTC, skitt requested changes

2022-11-09 08:45 UTC, skitt commented on Makefile
> +package-charts: submariner-k8s-broker-$(CHARTS_VERSION).tgz submariner-operator-$(CHARTS_VERSION).tgz
Phony targets reduce Make’s ability to calculate the work that needs to be done:

```suggestion
CHART_PACKAGES := submariner-k8s-broker-$(CHARTS_VERSION).tgz submariner-operator-$(CHARTS_VERSION).tgz
```

2022-11-09 08:45 UTC, skitt commented on Makefile
> +local-helm-repo: package-charts
```suggestion
local-helm-repo: $(CHART_PACKAGES)
```

2022-11-09 08:45 UTC, skitt commented on Makefile
> +	tar -zxf submariner-operator-$(CHARTS_VERSION).tgz -C $(HELM_REPO_LOCATION)
Avoid relying on a specific set of packages:

```suggestion
	for archive in $^; do \
	    tar xzf $$archive -C $(HELM_REPO_LOCATION) \
	done
```

2022-11-09 08:45 UTC, skitt commented on Makefile
> +release: package-charts
```suggestion
release: $(CHART_PACKAGES)
```

2022-11-14 13:10 UTC, skitt approved these changes

2022-11-14 13:10 UTC, merged