Add LH coredns permission to access Submariner resource
submariner-io/submariner-charts pull request #341
Opened 2023-03-19 03:33 UTC by tpantelis

2023-03-19 08:49 UTC, nyechiel commented
Can you explain, ideally in the commit message, why is this required?

2023-03-20 08:32 UTC, skitt requested changes

2023-03-20 08:32 UTC, skitt commented on submariner-operator/templates/rbac.yaml
> -  - apiGroups:
It makes sense to remove these, but please explain why in the commit message.

2023-03-21 16:20 UTC, dfarrell07 approved these changes

2023-03-22 10:34 UTC, nyechiel approved these changes

2023-03-23 11:19 UTC, tpantelis commented
@skitt Can you re-review?

2023-03-23 13:03 UTC, skitt approved these changes

2023-03-23 13:03 UTC, merged